### ISSUE TITLE
Extensions can't be found in Marketplace and not installed manually

### ISSUE THREAD

**Issue by pascalgross** [Catel/Catel.Templates#136]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

Visual Studio 2019

## Version of Library

not relevant

## Version of OS(s) listed above with issue

Windows 10 Pro 21H1

## Steps to Reproduce
1. Open Visual Studio Market Place
2. Search for Catel

## Expected Behavior
Extensions should show up as search result

## Actual Behavior
No search result is found

Alternative way: donload vsix file from online market place and install manually fails too.
I attach the log (unfortunately in german).
```
15.09.2021 18:51:55 - Microsoft VSIX Installer
15.09.2021 18:51:55 - -------------------------------------------
15.09.2021 18:51:55 - vsixinstaller.exe version:
15.09.2021 18:51:55 - 16.11.12
15.09.2021 18:51:55 - -------------------------------------------
15.09.2021 18:51:55 - Command line parameters:
15.09.2021 18:51:55 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\pg\Downloads\Catel.ProjectTemplates.WPF.Application (1).vsix
15.09.2021 18:51:55 - -------------------------------------------
15.09.2021 18:51:55 - Microsoft VSIX Installer
15.09.2021 18:51:55 - -------------------------------------------
15.09.2021 18:51:55 - Initializing Install...
15.09.2021 18:51:56 - Erweiterungsdetails...
15.09.2021 18:51:56 - 	Identifier         : Catel.ProjectTemplates.WPF.Application..957f7b56-3fbe-4b24-8257-6f59d6b890de
15.09.2021 18:51:56 - 	Name               : Catel - WPF - Application
15.09.2021 18:51:56 - 	Author             : Catel
15.09.2021 18:51:56 - 	Version            : 5.1.0.274
15.09.2021 18:51:56 - 	Description        : Project template to create an MVVM-based application for WPF using Catel.
15.09.2021 18:51:56 - 	Locale             : en-US
15.09.2021 18:51:56 - 	MoreInfoURL        : https://www.catelproject.com/
15.09.2021 18:51:56 - 	InstalledByMSI     : False
15.09.2021 18:51:56 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
15.09.2021 18:51:56 - 
15.09.2021 18:51:56 - 	SignatureState     : Unsigned
15.09.2021 18:51:56 - 	Unterstützte Produkte : 
15.09.2021 18:51:56 - 		Microsoft.VisualStudio.Pro
15.09.2021 18:51:56 - 			Version : [17.0,18.0)
15.09.2021 18:51:56 - 		Microsoft.VisualStudio.VSWinExpress
15.09.2021 18:51:56 - 			Version : [17.0,18.0)
15.09.2021 18:51:56 - 		Microsoft.VisualStudio.VSWinDesktopExpress
15.09.2021 18:51:56 - 			Version : [17.0,18.0)
15.09.2021 18:51:56 - 
15.09.2021 18:51:56 - 	Verweise           : 
15.09.2021 18:51:56 - 	Voraussetzungen    : 
15.09.2021 18:51:56 - 		-------------------------------------------------------
15.09.2021 18:51:56 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
15.09.2021 18:51:56 - 		Name         : .NET desktop development tools
15.09.2021 18:51:56 - 		Version      : [16.0,)
15.09.2021 18:51:56 - 
15.09.2021 18:51:56 - Signaturdetails...
15.09.2021 18:51:56 - 	Extension is not signed.
15.09.2021 18:51:56 - 
15.09.2021 18:51:56 - Er wird nach passenden Produkten gesucht...
15.09.2021 18:51:56 - Installiertes Produkt gefunden - Globaler Pfad
15.09.2021 18:51:56 - Installiertes Produkt gefunden - Visual Studio Community 2019
15.09.2021 18:51:56 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, checking now.

**Comment by GeertvanHorrik** [comment]
It should be fixed, can you please let me know whether it works?

**Comment by pascalgross** [comment]
I'm unable to find any Catel related in the market place.
Is there a way I can download the updated vsix file to test?

**Comment by GeertvanHorrik** [comment]
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.RemoteControl.RemoteControlClient..ctor(Microsoft.VisualStudio.Utilities.Internal.IRegistryTools, System.String, System.String, System.String, Int32, Int32, Int32)'.
   at Microsoft.VisualStudio.Telemetry.TelemetryManifestManager.Start(String hostName, Boolean isDisposing)
   at Microsoft.VisualStudio.Telemetry.TelemetrySession.Start(Boolean checkPendingAsimovEvents)
   at Microsoft.VisualStudio.Sdk.VsixPublisher.TelemetryLogger.CreateTelemetrySession()
   at Microsoft.VisualStudio.Sdk.VsixPublisher.TelemetryLogger.get_TelemetrySession()
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Program.Main(String[] args)
VSSDK: error VsixPub0029 : An error occurred while communicating with the marketplace: UploadFile: (Catel - code snippets) Target 'Microsoft.VisualStudio.Pro' with version range '[16.0,18.0)' specifies 'amd64' as the target product architecture, but Visual Studio 2019 and below does not support 'amd64'. More info at http://aka.ms/VS2022ExtensionSupport
```

Checking how this can be fixed now. I hope we can prevent using 2 different packages...

**Comment by GeertvanHorrik** [comment]
They should be pushed now, can you check?

**Comment by pascalgross** [comment]
Great. I was able to update all extensions vida the Marketplace.
Thank you!
